export const GAMEPLAY_CONFIG = {
  map: {
    width: 1920,
    height: 1080,
  },
  network: {
    maxPlayers: 2,
    positionSyncIntervalMs: 50,
    positionSyncEpsilon: 0.5,
    remotePositionLerpRate: 14,
    remotePositionSnapDistance: 48,
  },
  visibility: {
    shroudColor: 0x8f979d,
    shroudAlpha: 0.46,
    fogDepth: 925,
    visionRadius: 240,
    enemyVisibilityPadding: 24,
  },
  influence: {
    gridWidth: 40,
    gridHeight: 22,
    updateIntervalFrames: 6,
    lineColor: 0x111111,
    lineAlpha: 0.92,
    lineThickness: 8,
    splineDensityMultiplier: 8,
  },
  cities: {
    backlineOffset: 140,
    influenceUnitsEquivalent: 10,
  },
  input: {
    dragThreshold: 10,
    previewPathPointSpacing: 4,
    commandPathPointSpacing: 50,
  },
  movement: {
    engagementMagnetDistance: 80,
    engagementHoldDistance: 120,
    magnetismSpeed: 14,
    allyCollisionPushSpeed: 180,
    allySoftSeparationDistance: 28,
    allySoftSeparationPushSpeed: 90,
  },
  combat: {
    battleJiggleSpeed: 44,
    battleJiggleFrequency: 0.018,
    contactDamagePerSecond: 12,
  },
  unit: {
    bodyWidth: 24,
    bodyHeight: 14,
    healthMax: 100,
    healthRedThreshold: 0.35,
  },
  spawn: {
    unitsPerSide: 10,
    lineWidth: 10,
    spacingAcross: 28,
    spacingDepth: 32,
    red: { x: 860, y: 540, rotation: Math.PI / 2 },
    blue: { x: 1060, y: 540, rotation: -Math.PI / 2 },
  },
} as const;
